version: "3"
networks:
  frontend:
  backend:

volumes:
  fpm-socket:
    driver: local

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/work:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
      - fpm-socket:/var/run/php-fpm:cached
    ports:
      - 8000:80
    networks:
      - frontend
    depends_on:
      - php

  php:
    build:
      context: ./docker/php
    volumes:
      - ./:/work:cached
      - ./docker/php/crontab/laravel:/var/spool/cron/crontabs/root:cached
      - ./docker/php/logs:/var/log/php:cached
      - ./docker/php/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
      - fpm-socket:/var/run/php-fpm:cached
    working_dir: /work
    depends_on:
      - mysql
    expose:
      - 9000
    networks:
      - frontend
      - backend

  mysql:
    build:
      context: ./docker/mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/mysql_data:/var/lib/mysql:cached
      - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:cached
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - frontend
      - backend

  workspace:
    build:
      context: ./docker/workspace
    depends_on:
      - mysql
    ports:
      - 9001:9001
    volumes:
      - ./:/work:cached
    working_dir: /work
    networks:
      - frontend
      - backend
